# Generated by Django 5.1.6 on 2025-02-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0004_remove_orders_no_of_items_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='food_items',
            new_name='name',
        ),
    ]
