# Generated by Django 5.1.6 on 2025-02-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0005_rename_food_items_fooditems_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='student',
        ),
    ]
