# Generated by Django 5.1.6 on 2025-02-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canteenapp.category'),
        ),
    ]
