# Generated by Django 5.1.6 on 2025-02-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0008_fooditems_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
    ]
