# Generated by Django 5.1.6 on 2025-04-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comments',
        ),
    ]
