# Generated by Django 5.1.6 on 2025-04-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0012_remove_feedback_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='f_stock',
        ),
    ]
